# Generated by Django 4.2 on 2023-04-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_credito_user_podefaturada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um usuário com este CNPJ.'}, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um usuário com este CPF.'}, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='endereco',
            field=models.CharField(blank=True, default=None, error_messages={'unique': 'Já existe um usuário com este Endereço.'}, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Já existe um usuário com este Nome.'}, max_length=255, unique=True),
        ),
    ]
